version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    links:
#      - db
#
#  db:
#    image: mariadb
#    expose:
#      - 3306
#    volumes:
#      - ./data/db:/var/lib/mysql
#    environment:
#      - MARIADB_ROOT_PASSWORD=root