version: 0.2

phases:
  install:
    runtime-versions:
      java: latest
    commands:
      - echo Installing packages...
      - chmod +x ./gradlew
  build:
    commands:
      - echo Build Starting...
      - ./gradlew build
  post_build:
    commands:
      - echo Build Success!

artifacts:
  files:
    - appspec.yml
    - '**/*'